### ISSUE TITLE
In sync mode promise never resolves on Win7

### ISSUE THREAD

**Issue by Joe-Kerr** [futomi/node-wav-player#1]
Hi Fotumi,

Do you accept pull requests?

There is a bug tested on Win7. In sync-mode, the player hangs after playback. The reason is because powershell never returns unless you add: this._proc.stdin.end(); (after line 65) - [see also](https://stackoverflow.com/a/10181488).

This does not happen on Win10. Howerver, adding ...stdin.end() on Win10 does not affect playback or promise resolution of the code below. So I guess it is safe to add.

**Code to reproduce**:

```
const player = require('node-wav-player');
const {join} = require("path");

console.log("play");

player.play({
	path: join(__dirname, './media/Nyan_Cat_min_loop.wav'), sync: true
}).then(() => {
	console.log('The wav file played successfully.'); //never reached
}).catch((error) => {
	console.error(error);
});	
```

https://github.com/futomi/node-wav-player/blob/de13ecf66177348dc7220aebc76359b4567d0b5b/lib/wav-player.js#L65

Best wishes
Joe

**Comment by futomi** [comment]
Sorry my reply is late. Thank you so much for your PR.

> Do you accept pull requests?

Yes, of course!  I've just merged your PR. Thanks again.
